name: e_commerce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.0.0  # Moved to correct section
  firebase_core: ^2.25.4
  cloud_firestore: ^4.13.3
  firebase_auth: ^4.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/CasualShirt.jpg
    - assets/images/banner.jpg
    - assets/images/FormalShirt.jpg  # Fixed asset path
    - assets/images/WomenDress.jpg  # Fixed asset path
    - assets/images/Jeans.jpg  # Fixed asset path
    - assets/images/Hoodie.jpg
    - assets/images/HalfShirt.jpg
    - assets/images/Profile.jpg
      
  fonts:
    - family: AmazonEmber
      fonts:
        - asset: assets/fonts/amazon-ember/Amazon Ember.ttf
        - asset: assets/fonts/amazon-ember/Amazon Ember Bold.ttf
